name: ClangFormat
on: push
jobs:
  ClangFormat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          clangFormatVersion: 16
